In [1]:
import pandas as pd
import numpy as np
import pdftotext
import os
import glob
import nltk

In [2]:
df = pd.read_excel("all_data.xlsx")

In [15]:
df.shape

(277, 112)

In [16]:
df.head()

Asia - Long  Asia - Net  Asia - Short  Beginning Balance  \
0          NaN         NaN           NaN          531250.00   
1          NaN         NaN           NaN          605514.45   
2          NaN         NaN           NaN          697346.19   
3          NaN         NaN           NaN          723538.84   
4          NaN         NaN           NaN          760465.85   

   Capital Call Amount ($)*  Capital Call (%)  Capital Reserve Balance ($)  \
0                       NaN               NaN                          NaN   
1                       NaN               NaN                          NaN   
2                       NaN               NaN                          NaN   
3                       NaN               NaN                          NaN   
4                       NaN               NaN                          NaN   

   Commitment  Consumer Discretionary - Long  Consumer Discretionary - Net  \
0   1250000.0                            NaN                           NaN   
1   1250000.0                            NaN                           NaN   
2   1250000.0                            NaN                           NaN   
3   1250000.0                            NaN                           NaN   
4   1250000.0                            NaN                           NaN   

              ...                  Category Name       Sub Category  \
0             ...               Capital Activity  Account Statement   
1             ...               Capital Activity  Account Statement   
2             ...               Capital Activity  Account Statement   
3             ...               Capital Activity  Account Statement   
4             ...               Capital Activity  Account Statement   

                                           File Name  \
0  Liverpool Investments L.P. - Henderson Holding...   
1  Liverpool Investments L.P. - Henderson Holding...   
2  Liverpool Investments L.P. - Henderson Holding...   
3  Liverpool Investments L.P. - Henderson Holding...   
4  Liverpool Investments L.P. - Henderson Holding...   

                                  Original File Name  Investment Structure  \
0           LiverpoolQuarterlyAcctStatements1148.pdf         Drawdown Fund   
1  Henderson Holding Group LLC - Liverpool Invest...         Drawdown Fund   
2  Henderson Holding Group LLC - Liverpool Invest...         Drawdown Fund   
3  Henderson Holding Group LLC - Liverpool Invest...         Drawdown Fund   
4  Henderson Holding Group LLC - Liverpool Invest...         Drawdown Fund   

         Last Modified     Modified by  Investment Legal Name  \
0  2019-01-26 17:01:27  canoe software                    NaN   
1  2019-01-26 17:01:27  canoe software                    NaN   
2  2019-01-26 17:01:28  canoe software                    NaN   
3  2019-01-26 17:01:28  canoe software                    NaN   
4  2019-01-26 17:01:28  canoe software                    NaN   

   Investment Extraction Alias      Entity Extraction Alias  
0                          NaN  Henderson Holding Group LLC  
1                          NaN  Henderson Holding Group LLC  
2                          NaN  Henderson Holding Group LLC  
3                          NaN  Henderson Holding Group LLC  
4                          NaN  Henderson Holding Group LLC  

[5 rows x 112 columns]

In [3]:
new_df = df[['Category Name', 'Sub Category', 'File Name']]

In [18]:
new_df.head()

Category Name       Sub Category  \
0  Capital Activity  Account Statement   
1  Capital Activity  Account Statement   
2  Capital Activity  Account Statement   
3  Capital Activity  Account Statement   
4  Capital Activity  Account Statement   

                                           File Name  
0  Liverpool Investments L.P. - Henderson Holding...  
1  Liverpool Investments L.P. - Henderson Holding...  
2  Liverpool Investments L.P. - Henderson Holding...  
3  Liverpool Investments L.P. - Henderson Holding...  
4  Liverpool Investments L.P. - Henderson Holding...

In [4]:
new_df = new_df[:-1]

In [20]:
len(new_df)

276

In [21]:
new_df['Sub Category'].unique()

array(['Account Statement', 'Distribution Notice', 'Call Notice',
       'Investor Letter', 'Fact Sheet'], dtype=object)

In [5]:
def category_to_numeric(x):
    if x == 'Account Statement':
        return 1
    elif x == 'Distribution Notice':
        return 2
    elif x == 'Call Notice':
        return 3
    else:
        return -1

In [6]:
new_df['category'] = new_df['Sub Category'].apply(category_to_numeric)

In [7]:
new_df['category'].unique()

array([ 1,  2,  3, -1])

In [8]:
new_df.head()

Category Name       Sub Category  \
0  Capital Activity  Account Statement   
1  Capital Activity  Account Statement   
2  Capital Activity  Account Statement   
3  Capital Activity  Account Statement   
4  Capital Activity  Account Statement   

                                           File Name  category  
0  Liverpool Investments L.P. - Henderson Holding...         1  
1  Liverpool Investments L.P. - Henderson Holding...         1  
2  Liverpool Investments L.P. - Henderson Holding...         1  
3  Liverpool Investments L.P. - Henderson Holding...         1  
4  Liverpool Investments L.P. - Henderson Holding...         1

In [26]:
new_df.shape

(276, 4)

In [9]:
new_df = new_df.sort_values(by='File Name').reset_index()

In [10]:
new_df.head()

index     Category Name       Sub Category  \
0    195  Capital Activity  Account Statement   
1    199  Capital Activity  Account Statement   
2    275  Capital Activity  Account Statement   
3    192  Capital Activity  Account Statement   
4    196  Capital Activity  Account Statement   

                                           File Name  category  
0  Arsenal Capital Group - Wenger Partners  - Acc...         1  
1  Arsenal Capital Group - Wenger Partners  - Acc...         1  
2  Arsenal Capital Group - Wenger Partners  - Acc...         1  
3  Arsenal Capital Group - Wenger Partners  - Acc...         1  
4  Arsenal Capital Group - Wenger Partners  - Acc...         1

In [29]:
len(new_df['File Name'])

276

In [11]:
pdfs = os.listdir("docs/raw_data/")
len(pdfs)

277

In [12]:
pdfs.sort()

In [13]:
pdfs

['.DS_Store',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2010-06-30.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2010-09-30.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2010-12-31.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2011-03-31.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2011-06-30.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2011-09-30.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2011-12-31.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2012-03-31.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2012-06-30.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2012-09-30.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2012-12-31.pdf',
 'Arsenal Capital Group - Wenger Partners  - Account Statement - 2013-03-31.pdf',
 '

In [14]:
new_df['file'] = pdfs[1:]

In [15]:
new_df.head()

index     Category Name       Sub Category  \
0    195  Capital Activity  Account Statement   
1    199  Capital Activity  Account Statement   
2    275  Capital Activity  Account Statement   
3    192  Capital Activity  Account Statement   
4    196  Capital Activity  Account Statement   

                                           File Name  category  \
0  Arsenal Capital Group - Wenger Partners  - Acc...         1   
1  Arsenal Capital Group - Wenger Partners  - Acc...         1   
2  Arsenal Capital Group - Wenger Partners  - Acc...         1   
3  Arsenal Capital Group - Wenger Partners  - Acc...         1   
4  Arsenal Capital Group - Wenger Partners  - Acc...         1   

                                                file  
0  Arsenal Capital Group - Wenger Partners  - Acc...  
1  Arsenal Capital Group - Wenger Partners  - Acc...  
2  Arsenal Capital Group - Wenger Partners  - Acc...  
3  Arsenal Capital Group - Wenger Partners  - Acc...  
4  Arsenal Capital Group - Wenger Partners  - Acc...

In [16]:
new_df['text'] = None

In [17]:
def convert_to_text(path=None):
    row = 0
    for file in glob.glob('docs/raw_data/*.pdf'):
        content = []
        with open(file, 'rb') as f:
            pdf = pdftotext.PDF(f)
    #         print (pdf)
            for page in pdf:
                page = page.replace('\n', ' ')
    #             print(page)
                content += nltk.sent_tokenize(page)
    #     print(content)
        new_df['text'][row] = content[0]
        row += 1

In [18]:
convert_to_text()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]


In [19]:
new_df.head(10)

index     Category Name       Sub Category  \
0    195  Capital Activity  Account Statement   
1    199  Capital Activity  Account Statement   
2    275  Capital Activity  Account Statement   
3    192  Capital Activity  Account Statement   
4    196  Capital Activity  Account Statement   
5    200  Capital Activity  Account Statement   
6    193  Capital Activity  Account Statement   
7    197  Capital Activity  Account Statement   
8    201  Capital Activity  Account Statement   
9    194  Capital Activity  Account Statement   

                                           File Name  category  \
0  Arsenal Capital Group - Wenger Partners  - Acc...         1   
1  Arsenal Capital Group - Wenger Partners  - Acc...         1   
2  Arsenal Capital Group - Wenger Partners  - Acc...         1   
3  Arsenal Capital Group - Wenger Partners  - Acc...         1   
4  Arsenal Capital Group - Wenger Partners  - Acc...         1   
5  Arsenal Capital Group - Wenger Partners  - Acc...         1   
6  Arsenal Capital Group - Wenger Partners  - Acc...         1   
7  Arsenal Capital Group - Wenger Partners  - Acc...         1   
8  Arsenal Capital Group - Wenger Partners  - Acc...         1   
9  Arsenal Capital Group - Wenger Partners  - Acc...         1   

                                                file  \
0  Arsenal Capital Group - Wenger Partners  - Acc...   
1  Arsenal Capital Group - Wenger Partners  - Acc...   
2  Arsenal Capital Group - Wenger Partners  - Acc...   
3  Arsenal Capital Group - Wenger Partners  - Acc...   
4  Arsenal Capital Group - Wenger Partners  - Acc...   
5  Arsenal Capital Group - Wenger Partners  - Acc...   
6  Arsenal Capital Group - Wenger Partners  - Acc...   
7  Arsenal Capital Group - Wenger Partners  - Acc...   
8  Arsenal Capital Group - Wenger Partners  - Acc...   
9  Arsenal Capital Group - Wenger Partners  - Acc...   

                                                text  
0                               Chelsea Partners ...  
1        Liverpool       Investments 6/30/2017 To...  
2                                 Newcastle Ventu...  
3  4/14/2016 Courtois Investment Group 5 Fulham R...  
4          Liverpool         Investments R 1/15/2...  
5                               Tottenham Hotspur...  
6                                                ...  
7                  Arsenal Capital Group R 9/12/2...  
8                         Capital Account Stateme...  
9                               Chelsea Partners ...

In [20]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import SVC

In [36]:
text_list = new_df['text'].tolist()
text_list = [re.sub(r'\d+', '', t) for t in text_list]
count_vect = CountVectorizer()
x_train_counts = count_vect.fit_transform(text_list)

In [32]:
# text_list
import re
text_list = [re.sub(r'\d+', '', t) for t in text_list]

In [52]:
text_list

['                             Chelsea Partners                                 Chelsea Partners Fund, L.P.                                           Capital Call                                          Due //                                  Henderson Holding Group   Total Commitment:                                               $,,   Paid-In Capital:                                                $,.   (including this payment)   Capital Call Amount:                                            $,.   Contribution % of Commitment:                                       .%   Remaining Commitment:                                          $,,. Please make sure to wire the requested funds no later than Saturday,  June  to our bank: Willian Bank Address:  Stamford Bridge London, United Kingdom Account Number:  Routing Number:  R',
 '      Liverpool       Investments // To: Henderson Holding Group LLC Re: Liverpool Investments L.P.                      Account Statement for Quarter ,         

In [37]:
x_train_counts

<276x299 sparse matrix of type '<class 'numpy.int64'>'
	with 8138 stored elements in Compressed Sparse Row format>

In [38]:
count_vect.get_feature_names()

['accordance',
 'accou',
 'account',
 'address',
 'affect',
 'agreement',
 'all',
 'allocations',
 'amended',
 'among',
 'amount',
 'amounts',
 'and',
 'announce',
 'ap',
 'approval',
 'apr',
 'april',
 'are',
 'arsenal',
 'article',
 'as',
 'ash',
 'assoc',
 'associa',
 'associates',
 'ast',
 'attribution',
 'aug',
 'aum',
 'balance',
 'bank',
 'be',
 'beginning',
 'benefit',
 'between',
 'bn',
 'bridge',
 'call',
 'capital',
 'case',
 'cash',
 'ce',
 'ch',
 'chelsea',
 'class',
 'close',
 'commitment',
 'commitments',
 'confidential',
 'confirm',
 'consequently',
 'contribution',
 'contributions',
 'courtois',
 'crystal',
 'currency',
 'date',
 'db',
 'dear',
 'dec',
 'december',
 'ded',
 'description',
 'desires',
 'differ',
 'different',
 'differing',
 'distribution',
 'distributions',
 'dividend',
 'drawdown',
 'due',
 'em',
 'en',
 'enclosed',
 'end',
 'ended',
 'ending',
 'equity',
 'er',
 'es',
 'est',
 'estimates',
 'et',
 'everton',
 'expenses',
 'family',
 'feb',
 'fee',
 'f

In [43]:
np.set_printoptions(threshold=np.nan)

In [44]:
x_train_counts.toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 3, 0, 0, 0, 0,
        2, 0, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 

In [47]:
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_counts)

In [55]:
tfidf_transformer.idf_

array([3.25672168, 4.05906815, 2.22956835, 3.25672168, 4.54457596,
       2.63503346, 2.67277379, 5.52540522, 3.67957853, 5.52540522,
       3.25672168, 2.63503346, 2.2051769 , 3.36592097, 3.32818064,
       4.83225804, 5.01457959, 5.52540522, 2.13538114, 3.1582816 ,
       4.54457596, 4.54457596, 4.05906815, 5.52540522, 4.05906815,
       5.52540522, 4.05906815, 5.52540522, 5.01457959, 5.52540522,
       2.08072272, 3.25672168, 4.83225804, 1.96057841, 4.05906815,
       5.52540522, 5.52540522, 2.88634789, 2.30652939, 1.36652213,
       5.52540522, 4.83225804, 4.05906815, 4.05906815, 2.41932489,
       5.52540522, 4.05906815, 1.81999646, 4.54457596, 5.52540522,
       4.83225804, 4.54457596, 2.61668432, 2.24199087, 2.7738699 ,
       3.91596731, 4.05906815, 2.69219187, 4.05906815, 2.98643135,
       5.01457959, 3.91596731, 4.05906815, 4.05906815, 4.54457596,
       5.52540522, 5.52540522, 5.52540522, 2.49688312, 2.4045098 ,
       4.54457596, 4.54457596, 2.54648006, 4.05906815, 4.05906

In [49]:
varietal_list = new_df['category'].tolist()
train_x, test_x, train_y, test_y = train_test_split(x_train_tfidf, varietal_list, test_size=0.3)

In [50]:
# clf = MultinomialNB().fit(train_x, train_y)
clf = SVC(kernel='linear').fit(train_x, train_y)
# clf = SVC(kernel='linear').fit(x_train_tfidf, varietal_list)
y_score = clf.predict(test_x)

In [60]:
y_score

array([1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1])

In [64]:
# test_y
d = {'category': y_score, 'predict': test_y}
pd.DataFrame(data=d).transpose()

0   1   2   3   4   5   6   7   8   9  ...  73  74  75  76  77  78  \
category   1   1   1   1   3   1   1   1   1   1 ...   1   1   1   1   3   1   
predict    3   1   1   2   3   3   3   2   3   1 ...   1   1   3   2   1   3   

          79  80  81  82  
category   3   1   1   1  
predict    3   1   1   3  

[2 rows x 83 columns]

In [58]:
y_score != test_y

array([ True, False, False,  True, False,  True,  True,  True,  True,
       False, False,  True,  True, False,  True, False,  True, False,
        True,  True, False, False, False,  True, False,  True,  True,
       False,  True,  True,  True,  True, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False,  True, False,  True, False,  True, False,
       False, False, False,  True, False, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True, False, False,
       False,  True])

In [51]:
np.mean(y_score != test_y)

0.4939759036144578

In [65]:
new_pdfs = pdfs = os.listdir("docs/new/")
new_pdfs.sort()

In [66]:
df2 = pd.DataFrame(columns=['index', 'Category Name', 'Sub Category', 'File Name', 'category',
       'file', 'text'])

In [67]:
for file in new_pdfs:
    sub_category = file.split(' - ')[-2]
    content = []
    with open("docs/new/"+file, 'rb') as f:
        pdf = pdftotext.PDF(f)
#         print (pdf)
        for page in pdf:
            page = page.replace('\n', ' ')
#             print(page)
            content += nltk.sent_tokenize(page)
#     print(content)
#     new_df['text'][row] = content[0]
    cat = category_to_numeric(sub_category)
    df2 = df2.append({'Sub Category': sub_category, 'file': file, 'text': content[0], 'category': cat}, ignore_index=True)

In [68]:
new_df.append(df2)

index     Category Name         Sub Category  \
0    195  Capital Activity    Account Statement   
1    199  Capital Activity    Account Statement   
2    275  Capital Activity    Account Statement   
3    192  Capital Activity    Account Statement   
4    196  Capital Activity    Account Statement   
5    200  Capital Activity    Account Statement   
6    193  Capital Activity    Account Statement   
7    197  Capital Activity    Account Statement   
8    201  Capital Activity    Account Statement   
9    194  Capital Activity    Account Statement   
10   198  Capital Activity    Account Statement   
11   202  Capital Activity    Account Statement   
12    24  Capital Activity          Call Notice   
13   112  Capital Activity          Call Notice   
14   116  Capital Activity          Call Notice   
15    23  Capital Activity          Call Notice   
16   109  Capital Activity          Call Notice   
17   113  Capital Activity          Call Notice   
18   118  Capital Activity          Call Notice   
19   107  Capital Activity          Call Notice   
20   110  Capital Activity          Call Notice   
21   114  Capital Activity          Call Notice   
22   117  Capital Activity          Call Notice   
23   108  Capital Activity          Call Notice   
24   111  Capital Activity          Call Notice   
25   115  Capital Activity          Call Notice   
26   143  Capital Activity  Distribution Notice   
27   141  Capital Activity  Distribution Notice   
28   144  Capital Activity  Distribution Notice   
29   142  Capital Activity  Distribution Notice   
..   ...               ...                  ...   
70   NaN               NaN    Account Statement   
71   NaN               NaN    Account Statement   
72   NaN               NaN    Account Statement   
73   NaN               NaN    Account Statement   
74   NaN               NaN    Account Statement   
75   NaN               NaN    Account Statement   
76   NaN               NaN    Account Statement   
77   NaN               NaN    Account Statement   
78   NaN               NaN    Account Statement   
79   NaN               NaN    Account Statement   
80   NaN               NaN    Account Statement   
81   NaN               NaN    Account Statement   
82   NaN               NaN    Account Statement   
83   NaN               NaN    Account Statement   
84   NaN               NaN    Account Statement   
85   NaN               NaN    Account Statement   
86   NaN               NaN    Account Statement   
87   NaN               NaN    Account Statement   
88   NaN               NaN    Account Statement   
89   NaN               NaN    Account Statement   
90   NaN               NaN    Account Statement   
91   NaN               NaN    Account Statement   
92   NaN               NaN    Account Statement   
93   NaN               NaN    Account Statement   
94   NaN               NaN    Account Statement   
95   NaN               NaN    Account Statement   
96   NaN               NaN    Account Statement   
97   NaN               NaN    Account Statement   
98   NaN               NaN    Account Statement   
99   NaN               NaN    Account Statement   

                                            File Name category  \
0   Arsenal Capital Group - Wenger Partners  - Acc...        1   
1   Arsenal Capital Group - Wenger Partners  - Acc...        1   
2   Arsenal Capital Group - Wenger Partners  - Acc...        1   
3   Arsenal Capital Group - Wenger Partners  - Acc...        1   
4   Arsenal Capital Group - Wenger Partners  - Acc...        1   
5   Arsenal Capital Group - Wenger Partners  - Acc...        1   
6   Arsenal Capital Group - Wenger Partners  - Acc...        1   
7   Arsenal Capital Group - Wenger Partners  - Acc...        1   
8   Arsenal Capital Group - Wenger Partners  - Acc...        1   
9   Arsenal Capital Group - Wenger Partners  - Acc...        1   
10  Arsenal Capital Group - Wenger Partners  - Acc...        1   
11  Arsenal Capital Group - Wenger Partners  - A

In [69]:
text_list = new_df['text'].tolist()
count_vect = CountVectorizer()
x_train_counts = count_vect.fit_transform(text_list)

In [70]:
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_counts)

In [71]:
train_x, test_x, train_y, test_y = train_test_split(x_train_tfidf, varietal_list, test_size=0.3)

In [72]:
clf = SVC(kernel='linear').fit(train_x, train_y)
y_score = clf.predict(test_x)

In [73]:
np.mean(y_score != test_y)

0.5421686746987951

In [74]:
d2 = {'category': y_score, 'predict': test_y}
pd.DataFrame(data=d2).transpose()

0   1   2   3   4   5   6   7   8   9  ...  73  74  75  76  77  78  \
category   1   1   1   1   1   1   1   1   1   1 ...   1   1   1   1   1   1   
predict    1   1   1   3   1   1   1   1   1   1 ...   3   3   1   2   1   3   

          79  80  81  82  
category   1   1   1   1  
predict    1   1  -1   2  

[2 rows x 83 columns]